version = 1
disable_existing_loggers = false


# core logger
[handlers.consoleHandler]
level="DEBUG"
class = "logging.StreamHandler"
formatter = "consoleFormatter"

[handlers.coreHandler]
level="DEBUG"
class="logging.handlers.RotatingFileHandler"
filename = "logs/core/core.log"
maxBytes = 104857600
backupCount = 5
formatter = "coreFormatter"

[formatters.consoleFormatter]
format = "%(levelname)s - %(name)s - %(asctime)s - %(module)s - %(message)s"
datefmt = "%Y-%m-%d %H-%M-%S"

[formatters.coreFormatter]
format = "%(levelname)s - %(name)s - %(asctime)s - %(module)s - %(process)d - %(thread)d - %(message)s"
datefmt = "%Y-%m-%d %H-%M-%S"


[loggers.core]
handlers = ["coreHandler", "consoleHandler"]
level = "DEBUG"
propagate = true

# elasticsearch logger
[handlers.elasticsearchHandler]
level="DEBUG"
class="logging.handlers.RotatingFileHandler"
filename = "logs/elasticsearch/elasticsearch.log"
maxBytes = 104857600
backupCount = 5
formatter = "elasticsearchFormatter"

[formatters.elasticsearchFormatter]
format = "%(levelname)s - %(name)s - %(asctime)s - %(module)s - %(process)d - %(thread)d - %(message)s"
datefmt = "%Y-%m-%d %H-%M-%S"

[loggers.elasticsearch]
handlers = ["elasticsearchHandler", "consoleHandler"]
level = "INFO"
propagate = true
